### ISSUE TITLE
NPX cli tool deployment

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#12]
Finalize the configuration of the CLI tool and publish under the jsPsych organization. 

Prior to publishing, will need to figure out the flow and documentation for the two different tools. Lastly, will need to figure out why running `npx jspsych-metadata-cli` is crashing when running outside of a node project.
```[tasklist]
### Tasks
- [ ] https://github.com/jspsych/metadata/issues/15
- [x] Debug npx jspsych-metadata-cli failing outside of node repository (similar error to the current build for metadata - npm error Cannot destructure property 'package' of 'node.target' as it is null.)
- [x] Configure the npx jspsych-metadata-cli under the @jspsych organization on npm
```
