### ISSUE TITLE
Removing messages from the CLI prompting tool

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#13]
Should delete the messages with the .json files and fetching from the normal output. Should include a verbose flag with the files that will then include this information and reformat CLI to allow for this option.

```[tasklist]
### Tasks
- [x] Comment out the messages that display the data
- [x] Consolidate to display the number of files that succeeded vs failed and include short error messages on what is succeeding and failing
- [x] Add a verbose mode
```

**Comment by vzhang03** [comment]
Completed this for the CLI module and CLI is ready for testing and documentation. Could incorporate validator or add one more verbose message for reading data but seems unnecessary.
