### ISSUE TITLE
Adjusting userflow of frontend to be less technical and more informative

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#14]
```[tasklist]
### Tasks
- [x] Separate data and metadata prompting screens and make the button be closer to a continue
- [x] Create a number that tracks the pages before viewing the metadata
- [x] Create a prompt that will ask for the project name, description and author and not require you to click through fields
- [x] Reformat the page flow to load description and name after reading instead of skipping page 2
- [x] Create an author screen after project information that will load a list of current authors
- [x] Give the author screen functionality to dynamically add more authors and act as form for adding authors
- [x] Add a back button all of the previous screens and ability to upload more data on the last screen
```
