### ISSUE TITLE
Publish metadata 0.0.1

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#17]
Publish soon to be incorporated within datapipe architecture. 

```[tasklist]
### Tasks
- [x] Adjust package.json to reference the metadata index bin prior to publishing. This only applies if need to publish entire repo.
- [x] Adjusting the build file to configure the index.browser.js to export metadata ([reference](https://esbuild.github.io/api/#global-name)).
- [x] Figure out the importing of the index.iife.js file
- [x] Testing the package in current v8 branches with data
- [ ] https://github.com/jspsych/metadata/issues/4
- [x] Trimming down index.browser.js and index.browser.min.js, rest of cjs and js files used in CLI and frontend along with .d.ts files.
- [x] Update changeset and test so that the published version can be run through unpkg and can be used for jsPsych HTML experiments in the initial brainstormed form.
```
