### ISSUE TITLE
Overhauling the PreviewOptions screen

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#18]
Separated from [issue 14](https://github.com/jspsych/metadata/issues/14) because of the size and unrelated UI changes.

```[tasklist]
### Tasks
- [x] Change the preview to display in a more readable format that doesn't resemble .json
- [x] Adjust the metadata module to write a method allow for returning user-friendly metadata to display.
- [x] Adjust the preview to mimic the list interface and allow for easy adding, delete and edit of existing metadata or new fields
- [x] Design a way to encourage selecting preselect options and make filing the fields less important
```
