### ISSUE TITLE
Final frontend updates prior to merge/publish

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#28]
```[tasklist]
### Tasks
- [x] Include a hover that will display the other variable information when hovering over the specific button
- [x] Styling and finalizing information to be displayed in the hover
- [x] Allow to edit as description as json text and stringify and unstringify -> catch errors and use old if broken
- [x] Possibly do a similar fix for levels or just make it so that unable to edit levels?
- [x] Back button for the introductory prompting screen
- [x] Styling popups to be more usable by adding spacing
- [x] Make it so that doesn't display variable, change the information displayed in the button itself
- [x] Style the hover button and the gray text
- [x] Fix styling so when popups grow bigger can scroll to both sides
```
