### ISSUE TITLE
After publishing frontend refactor frontend and clean up code

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#30]
Should be done in tandem with [documentation](https://github.com/jspsych/metadata/issues/6).

```[tasklist]
### Tasks
- [ ] Delete unnecessary state references to use more general methods (openPopup vs set)
- [ ] Move list items into components
- [ ] Combining list items with list popup?
```
