### ISSUE TITLE
Finishing documentation for metadata package

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#4]
Update documentation for the new methods in the metadata package that handles generation and parsing. Update documentation pre-migration from the jsPsych main repo.

Will create a specific task list when addressing this issue.
```[tasklist]
### Tasks
- [x] Once figure out the configuration, create documentation about using metadata
- [x] Document methods and check that existing ones are correct with new changes in the README.md
- [x] Update link in metadata to reference new pushed unpkg link to load script.
```
